// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBH083F-3jZ5ameCVfDJKbwYnD2xiEVnc',
    appId: '1:398175482458:web:70cac0a59f5f61703fde63',
    messagingSenderId: '398175482458',
    projectId: 'tcc-aplicatico',
    authDomain: 'tcc-aplicatico.firebaseapp.com',
    storageBucket: 'tcc-aplicatico.firebasestorage.app',
    measurementId: 'G-Q5S7QXQT5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRTNFzG54t82QIPy0Jb9UAxZpkjKRyZmI',
    appId: '1:398175482458:android:74199987f93537323fde63',
    messagingSenderId: '398175482458',
    projectId: 'tcc-aplicatico',
    storageBucket: 'tcc-aplicatico.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDfE8GqGJvAUww5r_ozDe-WwY0acOuz64',
    appId: '1:398175482458:ios:f99a099f0e3c8be43fde63',
    messagingSenderId: '398175482458',
    projectId: 'tcc-aplicatico',
    storageBucket: 'tcc-aplicatico.firebasestorage.app',
    iosBundleId: 'com.example.src',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDfE8GqGJvAUww5r_ozDe-WwY0acOuz64',
    appId: '1:398175482458:ios:f99a099f0e3c8be43fde63',
    messagingSenderId: '398175482458',
    projectId: 'tcc-aplicatico',
    storageBucket: 'tcc-aplicatico.firebasestorage.app',
    iosBundleId: 'com.example.src',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBH083F-3jZ5ameCVfDJKbwYnD2xiEVnc',
    appId: '1:398175482458:web:a4442a53d31780de3fde63',
    messagingSenderId: '398175482458',
    projectId: 'tcc-aplicatico',
    authDomain: 'tcc-aplicatico.firebaseapp.com',
    storageBucket: 'tcc-aplicatico.firebasestorage.app',
    measurementId: 'G-4TW98RVZP0',
  );

}